FROM node:18-alpine

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package.json package-lock.json ./

# Install dependencies, including dev dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Command to run the application using nodemon
CMD ["npx", "nodemon", "index.js"]
